parent=keycloak.v3
import=common/lynxton

styles=css/brand.css css/console.css
logo=/img/logo.png
logoUrl=https://www.lynxtoncloud.com/
favIcon=/img/favicon.ico
favIconType=image/x-icon
title=灵通云账户中心 | LynxtonCloud
description=管理灵通云账户资料、登录方式与设备。
darkMode=false
